// Static-index backend for the web (GitHub Pages) build. The provider indexes
// are generated by `src-tauri/examples/dump_web_index.rs` and shipped as JSON,
// so the site works without any server or CORS-enabled upstream API.
import {
  matchEntries,
  parseAndExpand,
  rankResults,
  type IndexEntryLike,
} from "./searchEngine";
import type { ProviderInfo, ProviderStatus, SearchResponse, SearchResult } from "./types";

export interface ManifestEntry {
  id: string;
  name: string;
  homepage: string;
  experimental: boolean;
  count: number;
  updated_at: string;
  file: string;
}

interface ProviderIndex {
  source_id: string;
  source_name: string;
  homepage: string;
  experimental: boolean;
  updated_at: string;
  entries: IndexEntryLike[];
}

const base = import.meta.env.BASE_URL || "/";
const STORAGE_KEY = "sve.webIndex.v1";

let manifest: ManifestEntry[] | null = null;
const loaded = new Map<string, ProviderIndex>();

function indexUrl(file: string): string {
  return `${base.replace(/\/$/, "")}/index/${file}`;
}

export async function loadManifest(): Promise<ManifestEntry[]> {
  if (manifest) return manifest;
  const res = await fetch(`${base.replace(/\/$/, "")}/index/manifest.json`, {
    cache: "no-cache",
  });
  if (!res.ok) throw new Error(`failed to load index manifest (${res.status})`);
  manifest = (await res.json()) as ManifestEntry[];
  return manifest;
}

async function loadProvider(id: string): Promise<ProviderIndex | null> {
  if (loaded.has(id)) return loaded.get(id) as ProviderIndex;
  const m = (await loadManifest()).find((x) => x.id === id);
  if (!m) return null;

  // Try the localStorage cache first.
  try {
    const cached = localStorage.getItem(`${STORAGE_KEY}:${m.updated_at}:${id}`);
    if (cached) {
      const parsed = JSON.parse(cached) as ProviderIndex;
      loaded.set(id, parsed);
      return parsed;
    }
  } catch {
    /* ignore */
  }

  const res = await fetch(indexUrl(m.file));
  if (!res.ok) throw new Error(`failed to load ${m.file} (${res.status})`);
  const parsed = (await res.json()) as ProviderIndex;
  loaded.set(id, parsed);
  try {
    localStorage.setItem(`${STORAGE_KEY}:${m.updated_at}:${id}`, JSON.stringify(parsed));
  } catch {
    /* quota exceeded — memory cache is enough */
  }
  return parsed;
}

export async function webProviders(enabled: string[]): Promise<ProviderInfo[]> {
  const m = await loadManifest();
  return m.map((x) => ({
    id: x.id,
    name: x.name,
    homepage: x.homepage,
    experimental: x.experimental,
    indexed_items: x.count,
    last_updated: x.updated_at,
    enabled: enabled.includes(x.id),
  }));
}

export async function webSearch(
  rawQuery: string,
  enabled: string[]
): Promise<SearchResponse> {
  const q = parseAndExpand(rawQuery);
  const m = await loadManifest();

  const wanted = q.siteFilter
    ? m.filter((x) => x.id === q.siteFilter)
    : m.filter((x) => enabled.includes(x.id));

  const results: SearchResult[] = [];
  const statuses: ProviderStatus[] = [];

  await Promise.all(
    wanted.map(async (entry) => {
      try {
        const index = await loadProvider(entry.id);
        const found = index
          ? matchEntries(index.entries, index.source_id, index.source_name, q)
          : [];
        results.push(...found);
        statuses.push({
          id: entry.id,
          name: entry.name,
          homepage: entry.homepage,
          state: "done",
          count: found.length,
          error: null,
          indexed_items: entry.count,
          last_updated: entry.updated_at,
          experimental: entry.experimental,
          enabled: true,
        });
      } catch (e) {
        statuses.push({
          id: entry.id,
          name: entry.name,
          homepage: entry.homepage,
          state: "error",
          count: 0,
          error: String(e),
          indexed_items: entry.count,
          last_updated: entry.updated_at,
          experimental: entry.experimental,
          enabled: true,
        });
      }
    })
  );

  let filtered = results;
  if (q.typeFilter) filtered = filtered.filter((r) => r.result_type === q.typeFilter);

  const ranked = rankResults(q, filtered);

  // Include disabled providers as idle so the sidebar can show every source.
  const all = await loadManifest();
  const seen = new Set(statuses.map((s) => s.id));
  for (const x of all) {
    if (seen.has(x.id)) continue;
    statuses.push({
      id: x.id,
      name: x.name,
      homepage: x.homepage,
      state: "idle",
      count: 0,
      error: null,
      indexed_items: x.count,
      last_updated: x.updated_at,
      experimental: x.experimental,
      enabled: enabled.includes(x.id),
    });
  }
  statuses.sort((a, b) => a.name.localeCompare(b.name));

  return {
    query: rawQuery.trim(),
    expanded_terms: q.tokens,
    results: ranked,
    providers: statuses,
    total: ranked.length,
  };
}

/** Force a re-fetch of one provider index (used by "Refresh index"). */
export async function refreshWebProvider(id: string): Promise<void> {
  loaded.delete(id);
  const m = await loadManifest();
  const entry = m.find((x) => x.id === id);
  if (entry) {
    try {
      localStorage.removeItem(`${STORAGE_KEY}:${entry.updated_at}:${id}`);
    } catch {
      /* ignore */
    }
  }
  await loadProvider(id);
}

/** Drop every cached index (memory + localStorage). */
export async function clearWebCache(): Promise<number> {
  const m = await loadManifest();
  let removed = 0;
  for (const x of m) {
    try {
      const key = `${STORAGE_KEY}:${x.updated_at}:${x.id}`;
      if (localStorage.getItem(key)) {
        localStorage.removeItem(key);
        removed++;
      }
    } catch {
      /* ignore */
    }
  }
  loaded.clear();
  return removed;
}