// Static-index backend for the web (GitHub Pages) build. The provider indexes
// are generated by `src-tauri/examples/dump_web_index.rs` and shipped as JSON,
// so the site works without any server or CORS-enabled upstream API.
import {
  matchEntries,
  parseAndExpand,
  rankResults,
  type IndexEntryLike,
} from "./searchEngine";
import type { ProviderInfo, ProviderStatus, SearchResponse, SearchResult } from "./types";
import { providerCapability } from "./previewPolicy";
import { httpUrl } from "./urls";

export interface ManifestEntry {
  id: string;
  name: string;
  homepage: string;
  experimental: boolean;
  count: number;
  updated_at: string;
  file: string;
}

interface ProviderIndex {
  source_id: string;
  source_name: string;
  homepage: string;
  experimental: boolean;
  updated_at: string;
  entries: IndexEntryLike[];
}

const base = import.meta.env.BASE_URL || "/";
const STORAGE_KEY = "sve.webIndex.v1";

let manifest: ManifestEntry[] | null = null;
const loaded = new Map<string, ProviderIndex>();
let generation = 0;
let manifestRequest: Promise<ManifestEntry[]> | null = null;
const pending = new Map<string, Promise<ProviderIndex | null>>();

async function fetchJson(url: string): Promise<unknown> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15000);
  try {
    const res = await fetch(url, { cache: "no-cache", signal: controller.signal });
    if (!res.ok) throw new Error(`Failed to load index (${res.status})`);
    return await res.json();
  } finally { clearTimeout(timer); }
}

function validManifest(value: unknown): value is ManifestEntry[] {
  return Array.isArray(value) && value.every((v) => v && typeof v.id === "string" &&
    typeof v.name === "string" && typeof v.homepage === "string" && typeof v.updated_at === "string" &&
    typeof v.file === "string" && /^[\w-]+\.json$/.test(v.file) && Number.isFinite(v.count));
}

function validIndex(value: unknown, entry: ManifestEntry): value is ProviderIndex {
  const v = value as ProviderIndex | null;
  return !!v && v.source_id === entry.id && v.updated_at === entry.updated_at &&
    typeof v.source_name === "string" && Array.isArray(v.entries) && v.entries.every((e) => {
      try { httpUrl(e.url); } catch { return false; }
      return typeof e.title === "string" && typeof e.result_type === "string" &&
        Array.isArray(e.tags) && e.tags.every((t) => typeof t === "string") &&
        (e.description === null || typeof e.description === "string");
    });
}

function indexUrl(file: string): string {
  return `${base.replace(/\/$/, "")}/index/${file}`;
}

export async function loadManifest(): Promise<ManifestEntry[]> {
  if (manifest) return manifest;
  if (manifestRequest) return manifestRequest;
  const version = generation;
  const request = (async () => {
    let value: unknown;
    try {
      value = await fetchJson(indexUrl("manifest.json"));
      if (!validManifest(value)) throw new Error("Invalid index manifest");
      if (version === generation) {
        try { localStorage.setItem(`${STORAGE_KEY}:manifest`, JSON.stringify(value)); } catch { /* optional cache */ }
      }
    } catch (error) {
      try { value = JSON.parse(localStorage.getItem(`${STORAGE_KEY}:manifest`) ?? "null"); } catch { /* unavailable */ }
      if (!validManifest(value)) throw error;
    }
    if (version === generation) manifest = value as ManifestEntry[];
    return value as ManifestEntry[];
  })();
  manifestRequest = request;
  try { return await request; } finally { if (manifestRequest === request) manifestRequest = null; }
}

async function loadProvider(id: string): Promise<ProviderIndex | null> {
  if (loaded.has(id)) return loaded.get(id) as ProviderIndex;
  if (pending.has(id)) return pending.get(id)!;
  const request = fetchProvider(id);
  pending.set(id, request);
  try { return await request; } finally { if (pending.get(id) === request) pending.delete(id); }
}

async function fetchProvider(id: string): Promise<ProviderIndex | null> {
  const version = generation;
  const m = (await loadManifest()).find((x) => x.id === id);
  if (!m) return null;

  // Try the localStorage cache first.
  try {
    const cached = localStorage.getItem(`${STORAGE_KEY}:${m.updated_at}:${id}`);
    if (cached) {
      const parsed: unknown = JSON.parse(cached);
      if (validIndex(parsed, m)) {
        if (version === generation) loaded.set(id, parsed);
        return parsed;
      }
    }
  } catch {
    /* ignore */
  }

  const parsed = await fetchJson(indexUrl(m.file));
  if (!validIndex(parsed, m)) throw new Error(`Invalid index: ${id}`);
  if (version === generation) {
    loaded.set(id, parsed);
    try {
      for (const key of Object.keys(localStorage)) {
        if (key.startsWith(`${STORAGE_KEY}:`) && key.endsWith(`:${id}`)) localStorage.removeItem(key);
      }
      localStorage.setItem(`${STORAGE_KEY}:${m.updated_at}:${id}`, JSON.stringify(parsed));
    } catch { /* quota exceeded — memory cache is enough */ }
  }
  return parsed;
}

export async function webProviders(enabled: string[]): Promise<ProviderInfo[]> {
  const m = await loadManifest();
  return m.map((x) => ({
    id: x.id,
    name: x.name,
    homepage: x.homepage,
    preview_capability: providerCapability(x.id),
    experimental: x.experimental,
    indexed_items: x.count,
    last_updated: x.updated_at,
    enabled: enabled.includes(x.id),
  }));
}

export async function webSearch(
  rawQuery: string,
  enabled: string[],
  forceRefresh = false
): Promise<SearchResponse> {
  if (forceRefresh) await clearWebCache();
  const q = parseAndExpand(rawQuery);
  const m = await loadManifest();

  const wanted = q.siteFilter
    ? m.filter((x) => x.id === q.siteFilter)
    : m.filter((x) => enabled.includes(x.id));

  const results: SearchResult[] = [];
  const statuses: ProviderStatus[] = [];

  await Promise.all(
    wanted.map(async (entry) => {
      try {
        const index = await loadProvider(entry.id);
        const found = index
          ? matchEntries(index.entries, index.source_id, index.source_name, q)
          : [];
        results.push(...found);
        statuses.push({
          id: entry.id,
          name: entry.name,
          homepage: entry.homepage,
          preview_capability: providerCapability(entry.id),
          state: "done",
          count: found.length,
          error: null,
          indexed_items: entry.count,
          last_updated: entry.updated_at,
          experimental: entry.experimental,
          enabled: enabled.includes(entry.id),
        });
      } catch (e) {
        statuses.push({
          id: entry.id,
          name: entry.name,
          homepage: entry.homepage,
          preview_capability: providerCapability(entry.id),
          state: "error",
          count: 0,
          error: String(e),
          indexed_items: entry.count,
          last_updated: entry.updated_at,
          experimental: entry.experimental,
          enabled: enabled.includes(entry.id),
        });
      }
    })
  );

  let filtered = results;
  if (q.typeFilter) filtered = filtered.filter((r) => r.result_type === q.typeFilter);

  const ranked = rankResults(q, filtered);
  for (const status of statuses) status.count = ranked.filter((r) => r.source_id === status.id).length;

  // Include disabled providers as idle so the sidebar can show every source.
  const all = await loadManifest();
  const seen = new Set(statuses.map((s) => s.id));
  for (const x of all) {
    if (seen.has(x.id)) continue;
    statuses.push({
      id: x.id,
      name: x.name,
      homepage: x.homepage,
    preview_capability: providerCapability(x.id),
      state: "idle",
      count: 0,
      error: null,
      indexed_items: x.count,
      last_updated: x.updated_at,
      experimental: x.experimental,
      enabled: enabled.includes(x.id),
    });
  }
  statuses.sort((a, b) => a.name.localeCompare(b.name));

  return {
    query: rawQuery.trim(),
    expanded_terms: q.tokens,
    results: ranked,
    providers: statuses,
    total: ranked.length,
  };
}

/** Force a re-fetch of one provider index (used by "Refresh index"). */
export async function refreshWebProvider(id: string): Promise<void> {
  generation++;
  manifest = null;
  manifestRequest = null;
  pending.clear();
  loaded.delete(id);
  const m = await loadManifest();
  const entry = m.find((x) => x.id === id);
  if (entry) {
    try {
      localStorage.removeItem(`${STORAGE_KEY}:${entry.updated_at}:${id}`);
    } catch {
      /* ignore */
    }
  } else throw new Error(`Unknown provider: ${id}`);
  await loadProvider(id);
}

/** Drop every cached index (memory + localStorage). */
export async function clearWebCache(): Promise<number> {
  generation++;
  manifest = null;
  manifestRequest = null;
  pending.clear();
  let removed = 0;
  try {
    for (const key of Object.keys(localStorage)) {
      if (key.startsWith(`${STORAGE_KEY}:`)) {
        localStorage.removeItem(key);
        removed++;
      }
    }
  } catch { /* memory cache can still be cleared */ }
  loaded.clear();
  return removed;
}
