import { L, type LocalizedText } from "../learning/types.ts";
import type {
  GuidedStep,
  GuidedVisualizationDefinition,
  SceneFamily,
  VisualizationParameter,
} from "./types";

const step = (
  family: SceneFamily,
  stage: number,
  id: string,
  title: LocalizedText,
  explanation: LocalizedText,
  invariant: LocalizedText,
  equations: string[],
  controls: string[],
  highlights: string[],
  motion: "none" | "once" | "loop" = "none",
  duration = 4,
): GuidedStep => ({
  id,
  title,
  explanation,
  invariant,
  equations,
  controls: controls.map((parameterId) => ({ parameterId })),
  highlights,
  scene: { family, stage, motion, duration },
});
const parameter = (
  id: string,
  label: LocalizedText,
  min: number,
  max: number,
  initial: number,
  unit?: string,
  increment = 0.1,
): VisualizationParameter => ({
  id,
  label,
  min,
  max,
  initial,
  unit,
  step: increment,
});
const restoring = L(
  "Force and acceleration always point toward equilibrium.",
  "力与加速度始终指向平衡位置。",
  "力與加速度始終指向平衡位置。",
);
const ellipseInvariant = L(
  "The sum of the distances to the two foci is 2a.",
  "到两个焦点的距离之和恒为 2a。",
  "到兩個焦點的距離之和恆為 2a。",
);
const linearInvariant = L(
  "The columns of A are the images of the basis vectors.",
  "矩阵 A 的列就是基向量的像。",
  "矩陣 A 的列就是基向量的像。",
);

export const guidedShm: GuidedVisualizationDefinition = {
  id: "guided-shm",
  title: L("Guided SHM Explorer", "简谐振动引导探索", "簡諧振動引導探索"),
  conceptIds: ["simple-harmonic-motion"],
  renderer: "jsxgraph",
  kind: "guided-lesson",
  parameters: [
    parameter("A", L("Amplitude A", "振幅 A", "振幅 A"), 0.2, 2, 1.2, "m"),
    parameter(
      "k",
      L("Spring constant k", "劲度系数 k", "勁度係數 k"),
      0.5,
      8,
      2,
      "N/m",
    ),
    parameter("m", L("Mass m", "质量 m", "質量 m"), 0.5, 4, 1, "kg"),
    parameter(
      "phi",
      L("Initial phase φ", "初相位 φ", "初相位 φ"),
      0,
      6.28,
      0,
      "rad",
      0.01,
    ),
  ],
  presets: [],
  steps: [
    step(
      "shm",
      0,
      "equilibrium",
      L("Equilibrium", "平衡位置", "平衡位置"),
      L(
        "An unstretched horizontal spring exerts no force. A mass initially at rest here stays here. We assume a frictionless surface and an ideal spring.",
        "水平弹簧未伸缩时，弹力为零。物块若在此静止，就保持静止。模型假设水平面无摩擦、弹簧理想。",
        "水平彈簧未伸縮時，彈力為零。物塊若在此靜止，就保持靜止。模型假設水平面無摩擦、彈簧理想。",
      ),
      L(
        "Equilibrium means zero net force, not necessarily zero velocity.",
        "平衡表示合力为零，不一定表示速度为零。",
        "平衡表示合力為零，不一定表示速度為零。",
      ),
      ["x=0,\\quad F=0"],
      [],
      ["equilibrium"],
    ),
    step(
      "shm",
      1,
      "displacement",
      L("Displace the mass", "移开物块", "移開物塊"),
      L(
        "Drag the mass or change A. The displacement x is measured from equilibrium; right is positive. Hold it at rest before releasing.",
        "拖动物块或调整 A。位移 x 从平衡位置量起，向右为正。释放前，物块被保持在静止状态。",
        "拖動物塊或調整 A。位移 x 從平衡位置量起，向右為正。釋放前，物塊被保持在靜止狀態。",
      ),
      L(
        "Displacement is measured from equilibrium, not from the wall.",
        "位移从平衡位置量起，而非从墙壁量起。",
        "位移從平衡位置量起，而非從牆壁量起。",
      ),
      ["x=A>0"],
      ["A"],
      ["mass", "displacement"],
    ),
    step(
      "shm",
      2,
      "restoring-force",
      L("Restoring force", "回复力", "回復力"),
      L(
        "The force arrow points opposite to x. Stretching pulls left; compression pushes right. A larger k gives a larger force at the same displacement.",
        "力箭头与 x 方向相反：拉长时向左拉，压缩时向右推。同样位移下，k 越大，弹力越大。",
        "力箭頭與 x 方向相反：拉長時向左拉，壓縮時向右推。同樣位移下，k 越大，彈力越大。",
      ),
      restoring,
      ["F=-kx"],
      ["A", "k"],
      ["force", "displacement"],
    ),
    step(
      "shm",
      3,
      "acceleration",
      L("Newton's second law", "牛顿第二定律", "牛頓第二定律"),
      L(
        "Divide the net force by m. Acceleration points toward equilibrium and grows with displacement. Acceleration is not the same as velocity.",
        "合力除以 m 得到加速度。加速度指向平衡位置，其大小随位移增大。加速度与速度不是同一量。",
        "合力除以 m 得到加速度。加速度指向平衡位置，其大小隨位移增大。加速度與速度不是同一量。",
      ),
      restoring,
      ["ma=-kx", "a=-\\frac{k}{m}x=-\\omega^2x"],
      ["A", "k", "m"],
      ["force", "acceleration"],
    ),
    step(
      "shm",
      4,
      "release",
      L("Release", "释放", "釋放"),
      L(
        "Press Play. The force accelerates the mass toward equilibrium; speed increases while the force decreases. Playback stops at the first crossing so you can inspect it.",
        "点击播放。回复力使物块向平衡位置加速：速度增大，弹力却减小。播放停在首次穿越平衡位置处，便于观察。",
        "點擊播放。回復力使物塊向平衡位置加速：速度增大，彈力卻減小。播放停在首次穿越平衡位置處，便於觀察。",
      ),
      restoring,
      ["\\omega=\\sqrt{\\frac{k}{m}}"],
      ["A", "k", "m"],
      ["force", "velocity"],
      "once",
    ),
    step(
      "shm",
      5,
      "crossing",
      L("Cross equilibrium", "穿越平衡位置", "穿越平衡位置"),
      L(
        "At x = 0 the force and acceleration vanish, but the mass already has velocity. It passes through with maximum speed; zero force does not stop motion.",
        "x = 0 时弹力和加速度为零，但物块已有速度。它以最大速率穿过平衡位置；零合力不会使运动停止。",
        "x = 0 時彈力和加速度為零，但物塊已有速度。它以最大速率穿過平衡位置；零合力不會使運動停止。",
      ),
      L(
        "Zero force changes no velocity instantaneously.",
        "力为零时，速度不会瞬间改变。",
        "力為零時，速度不會瞬間改變。",
      ),
      ["x=0,\\quad F=0,\\quad |v|=A\\omega"],
      ["A", "k", "m"],
      ["velocity", "equilibrium"],
    ),
    step(
      "shm",
      6,
      "opposite",
      L("Opposite displacement", "另一侧的位移", "另一側的位移"),
      L(
        "At the left turning point the mass momentarily stops. The spring is compressed, so the force has reversed and now points right.",
        "在左侧转折点，物块瞬间停止。弹簧被压缩，回复力反向，指向右方。",
        "在左側轉折點，物塊瞬間停止。彈簧被壓縮，回復力反向，指向右方。",
      ),
      restoring,
      ["x=-A,\\quad v=0,\\quad F=+kA"],
      ["A", "k"],
      ["force", "displacement"],
    ),
    step(
      "shm",
      7,
      "periodicity",
      L("One full cycle", "一个完整周期", "一個完整週期"),
      L(
        "Play one full cycle. The same position and velocity return after T. Increase m or decrease k to lengthen the physical period; A does not change it.",
        "播放一个完整周期。经过 T 后，位置和速度都恢复原值。增加 m 或减小 k 会延长实际周期；A 不改变周期。",
        "播放一個完整週期。經過 T 後，位置和速度都恢復原值。增加 m 或減小 k 會延長實際週期；A 不改變週期。",
      ),
      L(
        "An ideal spring's period is independent of amplitude.",
        "理想弹簧的周期与振幅无关。",
        "理想彈簧的週期與振幅無關。",
      ),
      ["T=\\frac{2\\pi}{\\omega}=2\\pi\\sqrt{\\frac{m}{k}}"],
      ["A", "k", "m"],
      ["plot", "mass"],
      "once",
    ),
    step(
      "shm",
      8,
      "equation",
      L("Connect motion to the equation", "连接运动与方程", "連接運動與方程"),
      L(
        "A sets the excursion, ω sets the rate, and φ sets the initial phase. Compare the moving mass with its marker on x(t). This phase control now sets both initial position and velocity.",
        "A 决定位移范围，ω 决定变化速率，φ 决定初相位。对照物块与 x(t) 上的标记。此时相位同时设置初始位置与速度。",
        "A 決定位移範圍，ω 決定變化速率，φ 決定初相位。對照物塊與 x(t) 上的標記。此時相位同時設定初始位置與速度。",
      ),
      restoring,
      ["x(t)=A\\cos(\\omega t+\\varphi)", "\\omega=\\sqrt{\\frac{k}{m}}"],
      ["A", "k", "m", "phi"],
      ["plot", "mass"],
      "loop",
    ),
    step(
      "shm",
      9,
      "energy",
      L("Energy exchange", "能量交换", "能量交換"),
      L(
        "Potential energy is largest at the turning points; kinetic energy is largest at equilibrium. The bars exchange height while total energy stays fixed during motion. Changing A or k defines a new system with a new total energy.",
        "转折点处势能最大，平衡位置处动能最大。运动中两根能量条此消彼长，总能量保持不变。改变 A 或 k 会定义总能量不同的新系统。",
        "轉折點處勢能最大，平衡位置處動能最大。運動中兩根能量條此消彼長，總能量保持不變。改變 A 或 k 會定義總能量不同的新系統。",
      ),
      L(
        "For fixed parameters, kinetic plus potential energy is constant.",
        "参数固定时，动能与势能之和不变。",
        "參數固定時，動能與勢能之和不變。",
      ),
      ["K=\\tfrac12mv^2,\\quad U=\\tfrac12kx^2", "E=K+U=\\tfrac12kA^2"],
      ["A", "k", "m", "phi"],
      ["kinetic", "potential", "total"],
      "loop",
    ),
  ],
};

export const guidedEllipse: GuidedVisualizationDefinition = {
  id: "guided-ellipse",
  title: L(
    "Ellipse: definition to equation",
    "椭圆：从定义到方程",
    "橢圓：從定義到方程",
  ),
  conceptIds: ["ellipse"],
  renderer: "jsxgraph",
  kind: "guided-lesson",
  presets: [],
  parameters: [
    parameter("a", L("Semi-major axis a", "半长轴 a", "半長軸 a"), 1, 4, 3),
    parameter("c", L("Focal distance c", "半焦距 c", "半焦距 c"), 0, 3.9, 1.8),
    parameter(
      "theta",
      L("Point angle θ", "点的参数角 θ", "點的參數角 θ"),
      0,
      6.28,
      0.8,
      "rad",
      0.01,
    ),
  ],
  steps: [
    step(
      "ellipse",
      0,
      "foci",
      L("Two foci", "两个焦点", "兩個焦點"),
      L(
        "Place F₁ and F₂ symmetrically about the origin. c is half their separation. When c = 0 the foci coincide and the ellipse becomes a circle.",
        "把 F₁ 与 F₂ 对称放在原点两侧。c 是两焦点间距的一半。c = 0 时焦点重合，椭圆成为圆。",
        "把 F₁ 與 F₂ 對稱放在原點兩側。c 是兩焦點間距的一半。c = 0 時焦點重合，橢圓成為圓。",
      ),
      L(
        "The distance between the foci is 2c.",
        "两焦点间距为 2c。",
        "兩焦點間距為 2c。",
      ),
      ["F_1=(-c,0),\\quad F_2=(c,0)"],
      ["a", "c"],
      ["f1", "f2"],
    ),
    step(
      "ellipse",
      1,
      "point",
      L("A point and two distances", "一点与两段距离", "一點與兩段距離"),
      L(
        "Drag P or move θ. P is constrained to the candidate locus. Watch PF₁ and PF₂ change; measure both, not just the distance to the center.",
        "拖动 P 或调整 θ。P 被约束在候选轨迹上。观察 PF₁ 与 PF₂ 如何变化；应测量这两段距离，而非只测到中心的距离。",
        "拖動 P 或調整 θ。P 被約束在候選軌跡上。觀察 PF₁ 與 PF₂ 如何變化；應測量這兩段距離，而非只測到中心的距離。",
      ),
      L(
        "Both focal distances depend on P.",
        "两段焦距随 P 的位置改变。",
        "兩段焦距隨 P 的位置改變。",
      ),
      ["r_1=PF_1,\\quad r_2=PF_2"],
      ["a", "c", "theta"],
      ["p", "r1", "r2"],
    ),
    step(
      "ellipse",
      2,
      "sum",
      L("Keep the sum fixed", "固定距离之和", "固定距離之和"),
      L(
        "One distance increases while the other decreases. Their sum is 2a, greater than 2c. This is the geometric definition of the ellipse, not constant distance to its center.",
        "一段距离增大，另一段减小。它们的和是 2a，且大于 2c。这是椭圆的几何定义，并非到中心距离不变。",
        "一段距離增大，另一段減小。它們的和是 2a，且大於 2c。這是橢圓的幾何定義，並非到中心距離不變。",
      ),
      ellipseInvariant,
      ["PF_1+PF_2=2a,\\quad 0\\le c<a"],
      ["a", "c", "theta"],
      ["r1", "r2"],
    ),
    step(
      "ellipse",
      3,
      "locus",
      L("Trace the locus", "描出轨迹", "描出軌跡"),
      L(
        "Play or drag P to accumulate a trace. Every visited point satisfies the same distance sum. Changing a or c starts a fresh trace because the locus has changed.",
        "播放或拖动 P 来积累轨迹。每个经过的点都满足同一距离和。改变 a 或 c 会重新描线，因为轨迹已改变。",
        "播放或拖動 P 來積累軌跡。每個經過的點都滿足同一距離和。改變 a 或 c 會重新描線，因為軌跡已改變。",
      ),
      ellipseInvariant,
      ["P(\\theta)=(a\\cos\\theta,b\\sin\\theta)"],
      ["a", "c", "theta"],
      ["locus", "p"],
      "loop",
      8,
    ),
    step(
      "ellipse",
      4,
      "axes",
      L("Name a, b and c", "认识 a、b、c", "認識 a、b、c"),
      L(
        "a is the horizontal semi-axis, b the vertical semi-axis, and c the center-to-focus distance. They are half-lengths; a is not the full width.",
        "a 是水平半轴，b 是竖直半轴，c 是中心到焦点的距离。它们都是半长度；a 不是完整宽度。",
        "a 是水平半軸，b 是豎直半軸，c 是中心到焦點的距離。它們都是半長度；a 不是完整寬度。",
      ),
      ellipseInvariant,
      ["w=2a,\\quad h=2b"],
      ["a", "c", "theta"],
      ["axis-a", "axis-b", "axis-c"],
    ),
    step(
      "ellipse",
      5,
      "triangle",
      L("The right triangle", "直角三角形", "直角三角形"),
      L(
        "At the top vertex both focal distances equal a. The right triangle has legs b and c and hypotenuse a. Pythagoras therefore determines b; it is not an independent parameter.",
        "在上顶点，两段焦距均为 a。直角三角形的直角边为 b、c，斜边为 a。因此勾股关系确定 b，b 不是独立参数。",
        "在上頂點，兩段焦距均為 a。直角三角形的直角邊為 b、c，斜邊為 a。因此勾股關係確定 b，b 不是獨立參數。",
      ),
      L(
        "a² = b² + c², with a greater than c.",
        "a² = b² + c²，且 a 大于 c。",
        "a² = b² + c²，且 a 大於 c。",
      ),
      ["c^2=a^2-b^2", "b=\\sqrt{a^2-c^2}"],
      ["a", "c"],
      ["triangle", "axis-b", "axis-c"],
    ),
    step(
      "ellipse",
      6,
      "standard-equation",
      L("From distances to coordinates", "从距离到坐标", "從距離到座標"),
      L(
        "Write the two distances using coordinates, isolate one radical and square twice. Using b² = a² − c² gives the standard equation. Its intercepts are ±a and ±b; each plotted point satisfies both descriptions.",
        "用坐标写出两段距离，移项分离一个根式，再平方两次。代入 b² = a² − c² 得到标准方程。截距为 ±a 与 ±b；每个轨迹点同时满足两种描述。",
        "用座標寫出兩段距離，移項分離一個根式，再平方兩次。代入 b² = a² − c² 得到標準方程。截距為 ±a 與 ±b；每個軌跡點同時滿足兩種描述。",
      ),
      ellipseInvariant,
      [
        "\\sqrt{(x+c)^2+y^2}+\\sqrt{(x-c)^2+y^2}=2a",
        "\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1",
      ],
      ["a", "c", "theta"],
      ["locus", "axis-a", "axis-b"],
      "loop",
      8,
    ),
  ],
};

export const guidedLinear: GuidedVisualizationDefinition = {
  id: "guided-linear",
  title: L(
    "Linear transformation & determinant",
    "线性变换与行列式",
    "線性變換與行列式",
  ),
  conceptIds: ["linear-transformation", "determinant"],
  renderer: "jsxgraph",
  kind: "guided-lesson",
  parameters: [
    ...["a", "b", "c", "d"].map((id) =>
      parameter(
        id,
        L(`Matrix entry ${id}`, `矩阵元素 ${id}`, `矩陣元素 ${id}`),
        -2,
        2,
        ({ a: 1.5, b: 0.5, c: 0, d: 1 } as Record<string, number>)[id],
      ),
    ),
    parameter(
      "blend",
      L("Transformation progress", "变换进度", "變換進度"),
      0,
      1,
      1,
      undefined,
      0.01,
    ),
  ],
  presets: [
    {
      id: "rotation",
      title: L("Rotation (90°)", "旋转（90°）", "旋轉（90°）"),
      parameters: { a: 0, b: -1, c: 1, d: 0, blend: 1 },
    },
    {
      id: "scaling",
      title: L("Scaling", "缩放", "縮放"),
      parameters: { a: 2, b: 0, c: 0, d: 1.5, blend: 1 },
    },
    {
      id: "shear",
      title: L("Shear", "剪切", "剪切"),
      parameters: { a: 1, b: 1, c: 0, d: 1, blend: 1 },
    },
    {
      id: "reflection",
      title: L("Reflection", "反射", "反射"),
      parameters: { a: -1, b: 0, c: 0, d: 1, blend: 1 },
    },
    {
      id: "singular",
      title: L("Singular transform", "奇异变换", "奇異變換"),
      parameters: { a: 1, b: 2, c: 0.5, d: 1, blend: 1 },
    },
  ],
  steps: [
    step(
      "linear",
      0,
      "identity",
      L(
        "Identity and the unit square",
        "恒等变换与单位正方形",
        "恆等變換與單位正方形",
      ),
      L(
        "Start with e₁, e₂ and a square of area 1. The identity sends every point to itself. The original grid remains as a reference throughout this lesson.",
        "从 e₁、e₂ 和面积为 1 的正方形开始。恒等变换把每个点映到自身。原网格始终作为参照保留。",
        "從 e₁、e₂ 和面積為 1 的正方形開始。恆等變換把每個點映到自身。原網格始終作為參照保留。",
      ),
      L(
        "The initial area is 1 and the orientation is positive.",
        "初始面积为 1，取向为正。",
        "初始面積為 1，取向為正。",
      ),
      ["I=\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}"],
      [],
      ["square", "e1", "e2"],
    ),
    step(
      "linear",
      1,
      "basis",
      L("Transform the basis", "变换基向量", "變換基向量"),
      L(
        "A maps e₁ to its first column and e₂ to its second. Change one entry and inspect which basis image moves. Keep the unit square as a reference.",
        "A 把 e₁ 映到第一列，把 e₂ 映到第二列。改变一个元素，观察哪个基向量的像移动。单位正方形仍作为参照。",
        "A 把 e₁ 映到第一列，把 e₂ 映到第二列。改變一個元素，觀察哪個基向量的像移動。單位正方形仍作為參照。",
      ),
      linearInvariant,
      [
        "A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}",
        "Ae_1=(a,c),\\quad Ae_2=(b,d)",
      ],
      ["a", "b", "c", "d"],
      ["e1", "e2"],
    ),
    step(
      "linear",
      2,
      "grid",
      L("Move the whole grid", "变换整个网格", "變換整個網格"),
      L(
        "Play or scrub progress. Each point (x,y) follows xAe₁ + yAe₂. The preview interpolates B = (1−s)I + sA; it can become singular on the way even when A is invertible.",
        "播放或调整进度。每点 (x,y) 映为 xAe₁ + yAe₂。预览插值 B = (1−s)I + sA；即使 A 可逆，途中仍可能出现奇异矩阵。",
        "播放或調整進度。每點 (x,y) 映為 xAe₁ + yAe₂。預覽插值 B = (1−s)I + sA；即使 A 可逆，途中仍可能出現奇異矩陣。",
      ),
      L(
        "Linear combinations follow their transformed basis vectors.",
        "线性组合由变换后的基向量决定。",
        "線性組合由變換後的基向量決定。",
      ),
      ["B(s)=(1-s)I+sA", "B(x,y)=xBe_1+yBe_2"],
      ["a", "b", "c", "d", "blend"],
      ["grid", "e1", "e2"],
      "once",
    ),
    step(
      "linear",
      3,
      "parallelogram",
      L("Square to parallelogram", "正方形到平行四边形", "正方形到平行四邊形"),
      L(
        "The square's four corners map to 0, Ae₁, Ae₁+Ae₂ and Ae₂. Opposite edges stay parallel because linear maps preserve vector addition.",
        "正方形四个角映到 0、Ae₁、Ae₁+Ae₂、Ae₂。线性映射保持向量加法，因此对边仍平行。",
        "正方形四個角映到 0、Ae₁、Ae₁+Ae₂、Ae₂。線性映射保持向量加法，因此對邊仍平行。",
      ),
      linearInvariant,
      ["A(e_1+e_2)=Ae_1+Ae_2"],
      ["a", "b", "c", "d"],
      ["image", "e1", "e2"],
    ),
    step(
      "linear",
      4,
      "area",
      L("Measure area change", "测量面积变化", "測量面積變化"),
      L(
        "The parallelogram's area is |ad−bc|. Compare it with the original area 1. A shear changes the shape but leaves the area unchanged.",
        "平行四边形面积为 |ad−bc|，与原面积 1 对照。剪切改变形状，却保持面积不变。",
        "平行四邊形面積為 |ad−bc|，與原面積 1 對照。剪切改變形狀，卻保持面積不變。",
      ),
      L(
        "The unsigned area scale is |det(A)|.",
        "无向面积缩放因子是 |det(A)|。",
        "無向面積縮放因子是 |det(A)|。",
      ),
      [
        "\\det(A)=ad-bc",
        "\\frac{\\mathrm{Area}_{after}}{\\mathrm{Area}_{before}}=|\\det(A)|",
      ],
      ["a", "b", "c", "d"],
      ["image", "square"],
    ),
    step(
      "linear",
      5,
      "orientation",
      L("Orientation and collapse", "取向与维度塌缩", "取向與維度塌縮"),
      L(
        "Follow the labeled corners in order. Positive determinant preserves their orientation, negative reverses it, and zero makes the area collapse to a line or point. Area itself is never negative.",
        "按顺序观察标出的各角。行列式为正时保持取向，为负时反转，为零时面积塌缩成线或点。面积本身不会为负。",
        "按順序觀察標出的各角。行列式為正時保持取向，為負時反轉，為零時面積塌縮成線或點。面積本身不會為負。",
      ),
      L(
        "det(A) is an oriented area scale, not just an area.",
        "det(A) 是有向面积缩放因子，不只是面积。",
        "det(A) 是有向面積縮放因子，不只是面積。",
      ),
      ["\\det(A)>0:\\ +,\\quad\\det(A)<0:\\ -,\\quad\\det(A)=0:\\ 0"],
      ["a", "b", "c", "d"],
      ["image", "corner1", "corner2", "corner3"],
    ),
    step(
      "linear",
      6,
      "explore",
      L("Explore five transformations", "探索五种变换", "探索五種變換"),
      L(
        "Choose rotation, scaling, shear, reflection or a singular matrix. Predict the determinant's sign and area first, then inspect the result. Use Play or progress to compare intermediate B with the target A.",
        "选择旋转、缩放、剪切、反射或奇异矩阵。先预测行列式的符号与面积，再观察结果。播放或调整进度，对照中间矩阵 B 与目标 A。",
        "選擇旋轉、縮放、剪切、反射或奇異矩陣。先預測行列式的符號與面積，再觀察結果。播放或調整進度，對照中間矩陣 B 與目標 A。",
      ),
      L(
        "The determinant connects basis, area and orientation.",
        "行列式连接基向量、面积与取向。",
        "行列式連接基向量、面積與取向。",
      ),
      ["\\det(A)=ad-bc", "B(s)=(1-s)I+sA"],
      ["a", "b", "c", "d", "blend"],
      ["image", "grid"],
      "once",
    ),
  ],
};

export const visualizationDefinitions: readonly GuidedVisualizationDefinition[] =
  [guidedShm, guidedEllipse, guidedLinear];
const byId = new Map(
  visualizationDefinitions.map((definition) => [definition.id, definition]),
);
export const getVisualization = (id: string) => byId.get(id);
