import { L } from "../learning/types.ts";
export const workbenchText = {
  title: L("Concept Workbench", "概念工作台", "概念工作臺"),
  overview: L("Overview", "概览", "概覽"),
  learn: L("Learn", "学习", "學習"),
  visualize: L("Visualize", "可视化", "視覺化"),
  resources: L("Resources", "资源", "資源"),
  graph: L("Graph", "概念图", "概念圖"),
  inspector: L("Inspector", "上下文检查器", "上下文檢查器"),
  navigation: L("Navigation", "导航", "導覽"),
  trail: L("Concept Trail", "概念轨迹", "概念軌跡"),
  back: L("Previous concept", "上一个概念", "上一個概念"),
  forward: L(
    "Next concept in trail",
    "轨迹中的下一个概念",
    "軌跡中的下一個概念",
  ),
  prerequisites: L("Prerequisites", "先修概念", "先修概念"),
  related: L("Related", "相关概念", "相關概念"),
  next: L("Next concepts", "后续概念", "後續概念"),
  capabilities: L("Available capabilities", "可用能力", "可用能力"),
  read: L("Read", "阅读", "閱讀"),
  explore: L("Explore", "探索", "探索"),
  practice: L("Practice", "练习", "練習"),
  objectives: L("Learning objectives", "学习目标", "學習目標"),
  path: L("Learning Path", "学习路径", "學習路徑"),
  open: L("Open guided visualization", "打开引导式可视化", "開啟引導式視覺化"),
  close: L("Back to search results", "返回搜索结果", "返回搜尋結果"),
  search: L(
    "Search resources for this concept",
    "搜索此概念的资源",
    "搜尋此概念的資源",
  ),
  noLesson: L(
    "This concept has no native guided lesson yet. Explore its prerequisites and known resources.",
    "此概念暂无原生引导课程。可查看先修概念和已知资源。",
    "此概念暫無原生引導課程。可查看先修概念和已知資源。",
  ),
  noResources: L(
    "No indexed resources are annotated with this concept yet. Try a normal resource search.",
    "尚无标注此概念的索引资源。可尝试普通资源搜索。",
    "尚無標註此概念的索引資源。可嘗試一般資源搜尋。",
  ),
  loading: L("Loading…", "加载中…", "載入中…"),
  error: L(
    "Could not load this content. Retry to continue.",
    "无法加载此内容，请重试。",
    "無法載入此內容，請重試。",
  ),
  retry: L("Retry", "重试", "重試"),
  partial: L(
    "Some provider indexes are unavailable",
    "部分来源索引不可用",
    "部分來源索引不可用",
  ),
  all: L("All", "全部", "全部"),
  notes: L("Notes", "笔记", "筆記"),
  textbooks: L("Textbooks", "教材", "教材"),
  proofs: L("Proofs", "证明", "證明"),
  simulations: L("Simulations", "模拟", "模擬"),
  external: L("Open externally", "在外部打开", "在外部開啟"),
  textbook: L("External textbook reference", "外部教材引用", "外部教材引用"),
  subject: L("Subject", "学科", "學科"),
  concept: L("Concept", "概念", "概念"),
  lesson: L("Lesson", "课程", "課程"),
  visualization: L("Visualization", "可视化", "視覺化"),
  resource: L("Resource", "资源", "資源"),
  command: L("Command", "命令", "命令"),
  provider: L("Provider", "来源", "來源"),
  type: L("Resource type", "资源类型", "資源類型"),
  language: L("Language", "语言", "語言"),
  rights: L("Rights status", "权利状态", "權利狀態"),
  unknown: L("Unknown", "未知", "未知"),
  step: L("Step", "步骤", "步驟"),
  invariant: L("Invariant", "不变量", "不變量"),
  parameters: L("Parameters", "参数", "參數"),
  equation: L("Equation", "方程", "方程"),
  misconception: L(
    "Misconception to avoid",
    "需要避免的误解",
    "需要避免的誤解",
  ),
  observation: L("Observe", "观察", "觀察"),
  cause: L("Why", "原因", "原因"),
  consequence: L("What follows", "推论", "推論"),
  palette: L("Command Palette", "命令面板", "命令面板"),
  findCommand: L("Find a command", "查找命令", "尋找命令"),
  noCommands: L("No matching commands", "没有匹配命令", "沒有符合命令"),
  openSurface: L("Open", "打开", "開啟"),
  copy: L(
    "Copy canonical concept name",
    "复制规范概念名称",
    "複製標準概念名稱",
  ),
  go: L("Go to", "前往", "前往"),
  searchFocus: L("Focus universal search", "聚焦统一搜索", "聚焦統一搜尋"),
  resume: L("Resume Concept Session", "继续概念会话", "繼續概念工作階段"),
};
